from datetime import datetime,date
from sqlalchemy import String,Integer,Float,Date,DateTime,ForeignKey,Text,Boolean
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.db import Base
class User(Base):
    __tablename__='users'; id:Mapped[int]=mapped_column(primary_key=True); email:Mapped[str]=mapped_column(String(255),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); role:Mapped[str]=mapped_column(String(30),default='farmer'); is_active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
    profile=relationship('FarmerProfile',back_populates='user',uselist=False,cascade='all, delete-orphan'); crops=relationship('Crop',back_populates='user',cascade='all, delete-orphan'); diagnoses=relationship('Diagnosis',back_populates='user',cascade='all, delete-orphan'); chats=relationship('ChatMessage',back_populates='user',cascade='all, delete-orphan')
class FarmerProfile(Base):
    __tablename__='farmer_profiles'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),unique=True); full_name:Mapped[str]=mapped_column(String(150)); phone:Mapped[str|None]=mapped_column(String(30)); city:Mapped[str]=mapped_column(String(120),default=''); state:Mapped[str]=mapped_column(String(120),default=''); farm_size_acres:Mapped[float|None]=mapped_column(Float); soil_type:Mapped[str|None]=mapped_column(String(80)); latitude:Mapped[float|None]=mapped_column(Float); longitude:Mapped[float|None]=mapped_column(Float); user=relationship('User',back_populates='profile')
class Crop(Base):
    __tablename__='crops'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); crop_type:Mapped[str]=mapped_column(String(100)); variety:Mapped[str|None]=mapped_column(String(120)); area_acres:Mapped[float]=mapped_column(Float); sowing_date:Mapped[date|None]=mapped_column(Date); growth_stage:Mapped[str]=mapped_column(String(80),default='vegetative'); soil_type:Mapped[str|None]=mapped_column(String(80)); nitrogen:Mapped[float|None]=mapped_column(Float); phosphorus:Mapped[float|None]=mapped_column(Float); potassium:Mapped[float|None]=mapped_column(Float); soil_moisture:Mapped[float|None]=mapped_column(Float); notes:Mapped[str|None]=mapped_column(Text); status:Mapped[str]=mapped_column(String(30),default='active'); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); user=relationship('User',back_populates='crops'); history=relationship('CropHistory',back_populates='crop',cascade='all, delete-orphan')
class CropHistory(Base):
    __tablename__='crop_history'; id:Mapped[int]=mapped_column(primary_key=True); crop_id:Mapped[int]=mapped_column(ForeignKey('crops.id',ondelete='CASCADE'),index=True); event_type:Mapped[str]=mapped_column(String(60)); description:Mapped[str]=mapped_column(Text); recorded_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); crop=relationship('Crop',back_populates='history')
class Diagnosis(Base):
    __tablename__='diagnoses'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); crop_id:Mapped[int|None]=mapped_column(ForeignKey('crops.id',ondelete='SET NULL')); image_path:Mapped[str]=mapped_column(String(500)); predicted_class:Mapped[str]=mapped_column(String(200)); confidence:Mapped[float]=mapped_column(Float); status:Mapped[str]=mapped_column(String(40)); recommendation:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); user=relationship('User',back_populates='diagnoses')
class ChatMessage(Base):
    __tablename__='chat_messages'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); message:Mapped[str]=mapped_column(Text); response:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); user=relationship('User',back_populates='chats')
